In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
train = pd.read_csv("D:/ML on AGRICULTURE/train.csv")
test_data = pd.read_csv("D:/ML on AGRICULTURE/test.csv")

In [45]:
train.shape

(88858, 9)

In [46]:
test_data.shape

(59310, 8)

In [47]:
train.head()

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                      188          1          0                       1   
1                      209          1          0                       1   
2                      257          1          0                       1   
3                      257          1          1                       1   
4                      342          1          0                       1   

   Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                  0                0.0                  0       1   
1                  0                0.0                  0       2   
2                  0                0.0                  0       2   
3                  0                0.0                  0       2   
4                  0                0.0                  0       2   

   Crop_Damage  
0            0  
1            1  
2            1  
3            1  
4            1

In [48]:
train.corr(method ='pearson')

Estimated_Insects_Count  Crop_Type  Soil_Type  \
Estimated_Insects_Count                 1.000000  -0.088830  -0.056375   
Crop_Type                              -0.088830   1.000000  -0.287372   
Soil_Type                              -0.056375  -0.287372   1.000000   
Pesticide_Use_Category                 -0.079904   0.235779   0.032657   
Number_Doses_Week                      -0.102461  -0.192161   0.079447   
Number_Weeks_Used                       0.404464  -0.041473  -0.063444   
Number_Weeks_Quit                       0.299279  -0.233394   0.009364   
Season                                  0.002304   0.002161   0.002327   
Crop_Damage                             0.202888  -0.016495  -0.021997   

                         Pesticide_Use_Category  Number_Doses_Week  \
Estimated_Insects_Count               -0.079904          -0.102461   
Crop_Type                              0.235779          -0.192161   
Soil_Type                              0.032657           0.079447   
Pesticide_Use_Category                 1.000000          -0.003498   
Number_Doses_Week                     -0.003498           1.000000   
Number_Weeks_Used                      0.319399           0.116879   
Number_Weeks_Quit                     -0.554169          -0.037131   
Season                                 0.002811          -0.001401   
Crop_Damage                            0.175002          -0.030874   

                         Number_Weeks_Used  Number_Weeks_Quit    Season  \
Estimated_Insects_Count           0.404464           0.299279  0.002304   
Crop_Type                        -0.041473          -0.233394  0.002161   
Soil_Type                        -0.063444           0.009364  0.002327   
Pesticide_Use_Category            0.319399          -0.554169  0.002811   
Number_Doses_Week                 0.116879          -0.037131 -0.001401   
Number_Weeks_Used                 1.000000          -0.415646  0.003614   
Number_Weeks_Quit                -0.415646           1.000000  0.000595   
Season                            0.003614           0.000595  1.000000   
Crop_Damage                       0.213591          -0.133117 -0.000184   

                         Crop_Damage  
Estimated_Insects_Count     0.202888  
Crop_Type                  -0.016495  
Soil_Type                  -0.021997  
Pesticide_Use_Category      0.175002  
Number_Doses_Week          -0.030874  
Number_Weeks_Used           0.213591  
Number_Weeks_Quit          -0.133117  
Season                     -0.000184  
Crop_Damage                 1.000000

In [49]:
train['Crop_Damage'].value_counts()

0    74238
1    12307
2     2313
Name: Crop_Damage, dtype: int64

In [50]:
# Missing value in the dataset

train.isnull().sum()


Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64

In [51]:
test_data.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [52]:
train['Number_Weeks_Used'] = train['Number_Weeks_Used'].fillna(train['Number_Weeks_Used'].mode()[0])

In [53]:
test_data['Number_Weeks_Used'] = test_data['Number_Weeks_Used'].fillna(test_data['Number_Weeks_Used'].mode()[0])

In [54]:
train.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64

In [55]:
test_data.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [57]:
train.drop('ID',axis=1,inplace=True)


In [58]:
train.head()

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                      188          1          0                       1   
1                      209          1          0                       1   
2                      257          1          0                       1   
3                      257          1          1                       1   
4                      342          1          0                       1   

   Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                  0                0.0                  0       1   
1                  0                0.0                  0       2   
2                  0                0.0                  0       2   
3                  0                0.0                  0       2   
4                  0                0.0                  0       2   

   Crop_Damage  
0            0  
1            1  
2            1  
3            1  
4            1

In [60]:
test_data.drop('ID',axis=1,inplace=True)


In [61]:
test_data.head()

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                      188          1          1                       1   
1                      410          1          1                       1   
2                      626          1          0                       1   
3                      731          1          0                       1   
4                      789          0          0                       1   

   Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  
0                  0               20.0                  0       2  
1                  0                0.0                  0       2  
2                  0                0.0                  0       2  
3                  0                0.0                  0       2  
4                  0                0.0                  0       1

In [62]:
X_train, Y = train.drop(["Crop_Damage"], axis=1).values, train["Crop_Damage"].values
X_test = test_data.values

In [63]:
X_train.shape, Y.shape, X_test.shape

((88858, 8), (88858,), (59310, 8))

In [64]:
Y[:5]

array([0, 1, 1, 1, 1], dtype=int64)

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X_train, Y, train_size=0.8, test_size=0.2,
                                                                random_state=0)

# XBGBOOST

In [157]:
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import asarray
from numpy import mean
from numpy import std

my_model_1 = XGBClassifier(n_estimators=1000, num_class = 3) 

my_model_1.fit(X_train,y_train,early_stopping_rounds=5, 
             eval_set=[(X_valid, y_valid)], 
             verbose=False) 

my_model_1.score(X_train,y_train)

0.848394901949751

In [158]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import classification_report

predictions = my_model_1.predict(X_valid) 

print(classification_report(y_valid, predictions))

mae = mean_absolute_error(predictions,y_valid) 

print("Mean Absolute Error:" , mae)


              precision    recall  f1-score   support

           0       0.86      0.99      0.92     14848
           1       0.57      0.17      0.26      2473
           2       0.00      0.00      0.00       451

    accuracy                           0.85     17772
   macro avg       0.48      0.38      0.39     17772
weighted avg       0.80      0.85      0.80     17772

Mean Absolute Error: 0.17218095881161377


In [110]:
pred = my_model_1.predict(X_test)
pred[:10]


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [111]:
pred=(np.around(pred,decimals=0))
pred=pred.astype(int)

In [112]:
pred[:5]

array([1, 1, 1, 1, 1])

In [113]:
new_test = pd.read_csv("D:/ML on AGRICULTURE/test.csv")
result = pd.DataFrame(pred, new_test['ID'], columns=["Crop_Damage"])
result.to_csv("xgb500.csv")

# CATBOOST

In [72]:
!pip install catboost

  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11434 sha256=c9b8f54f172be2a1917f2828bb4aec949048ad83189bf5b815156e547b147523
  Stored in directory: c:\users\jayita\appdata\local\pip\cache\wheels\f9\8d\8d\f6af3f7f9eea3553bc2fe6d53e4b287dad18b06a861ac56ddf
Successfully built retrying


In [124]:
from catboost import CatBoostClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import asarray
from numpy import mean
from numpy import std

model = CatBoostClassifier(verbose=0, n_estimators=100)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')

print('Accuracy: %.6f (%.6f)' % (mean(n_scores), std(n_scores)))

model.fit(X_train,y_train,early_stopping_rounds=5, 
             eval_set=[(X_valid, y_valid)], 
             verbose=False) 

model.score(X_train,y_train)

Accuracy: 0.845497 (0.002008)


0.8483104971443041

In [125]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import classification_report

predictions = model.predict(X_valid) 
print(classification_report(y_valid, predictions))

mae = mean_absolute_error(predictions,y_valid) 

print("Mean Absolute Error:" , mae)

              precision    recall  f1-score   support

           0       0.86      0.99      0.92     14848
           1       0.58      0.16      0.25      2473
           2       0.20      0.00      0.00       451

    accuracy                           0.85     17772
   macro avg       0.55      0.38      0.39     17772
weighted avg       0.80      0.85      0.80     17772

Mean Absolute Error: 0.1727999099707405


In [93]:
pred = model.predict(X_test)
pred[0]
pred=(np.around(pred,decimals=0))
pred=pred.astype(int)
pred[-5:]

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [94]:
new_test = pd.read_csv("D:/ML on AGRICULTURE/test.csv")
result = pd.DataFrame(pred, new_test['ID'], columns=["Crop_Damage"])
result.to_csv("submission3-catboost500.csv")

# LGBM

In [114]:
!pip install lightgbm

In [150]:
from lightgbm import LGBMClassifier
model_lgbm = LGBMClassifier(verbose=0, n_estimators=1000,learning_rate=0.05, n_jobs=4)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model_lgbm, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')

print('Accuracy: %.6f (%.6f)' % (mean(n_scores), std(n_scores)))

model_lgbm.fit(X_train,y_train,early_stopping_rounds=5, 
             eval_set=[(X_valid, y_valid)], 
             verbose=False) 

model_lgbm.score(X_train,y_train)

Accuracy: 0.845502 (0.002546)


0.8485918464957938

In [151]:
predictions = model_lgbm.predict(X_valid) 
print(classification_report(y_valid, predictions))

mae = mean_absolute_error(predictions,y_valid) 

print("Mean Absolute Error:" , mae)

              precision    recall  f1-score   support

           0       0.86      0.99      0.92     14848
           1       0.58      0.17      0.27      2473
           2       0.00      0.00      0.00       451

    accuracy                           0.85     17772
   macro avg       0.48      0.39      0.39     17772
weighted avg       0.80      0.85      0.80     17772

Mean Absolute Error: 0.17066171505739366


C:\Users\Jayita\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [171]:
pred = model_lgbm.predict(X_test)
pred=(np.around(pred))
pred=pred.astype(int)
pred[-5:]

array([0, 0, 0, 0, 0])

In [172]:
new_test = pd.read_csv("D:/ML on AGRICULTURE/test.csv")
result = pd.DataFrame(pred, new_test['ID'], columns=["Crop_Damage"])
result.to_csv("D:/ML on Agriculture/lgbm_new.csv")

In [154]:
result = pd.concat([new_test['ID'],pd.Series(pred)],axis=1)
result.columns = ['ID','Crop_Damage']
result['Crop_Damage'].value_counts()

0    56832
1     2478
Name: Crop_Damage, dtype: int64

# RANDOMFOREST


In [128]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(oob_score = True, n_estimators=100)

model_rf.fit(X_train,y_train) 


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [129]:
predictions = model_rf.predict(X_valid) 
print(classification_report(y_valid, predictions))

mae = mean_absolute_error(predictions,y_valid) 

print("Mean Absolute Error:" , mae)

              precision    recall  f1-score   support

           0       0.87      0.95      0.90     14848
           1       0.38      0.20      0.26      2473
           2       0.11      0.05      0.07       451

    accuracy                           0.82     17772
   macro avg       0.45      0.40      0.41     17772
weighted avg       0.78      0.82      0.79     17772

Mean Absolute Error: 0.2014967364393428


# SVM 

In [133]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

clf = make_pipeline(StandardScaler(),LinearSVC(random_state=0, tol=1e-5))
clf.fit(X_train,y_train)

C:\Users\Jayita\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('linearsvc',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='squared_hinge', max_iter=1000,
                           multi_class='ovr', penalty='l2', random_state=0,
                           tol=1e-05, verbose=0))],
         verbose=False)

In [134]:
predictions = clf.predict(X_valid) 
print(classification_report(y_valid, predictions))

mae = mean_absolute_error(predictions,y_valid) 

print("Mean Absolute Error:" , mae)

              precision    recall  f1-score   support

           0       0.84      1.00      0.91     14848
           1       0.40      0.01      0.02      2473
           2       0.00      0.00      0.00       451

    accuracy                           0.83     17772
   macro avg       0.41      0.34      0.31     17772
weighted avg       0.76      0.83      0.76     17772

Mean Absolute Error: 0.19041188386225524


C:\Users\Jayita\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [170]:
pred = clf.predict(X_test)
pred=(np.around(pred,decimals=0))
pred=pred.astype(int)
pred[:5]
new_test = pd.read_csv("D:/ML on AGRICULTURE/test.csv")
result = pd.DataFrame(pred, new_test['ID'], columns=["Crop_Damage"])
result.to_csv("D:/ML on Agriculture/clf.csv")


In [135]:
from sklearn.linear_model import SGDClassifier

sgd = make_pipeline(StandardScaler(),
                    SGDClassifier(max_iter=1000, tol=1e-3))
sgd.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('sgdclassifier',
                 SGDClassifier(alpha=0.0001, average=False, class_weight=None,
                               early_stopping=False, epsilon=0.1, eta0=0.0,
                               fit_intercept=True, l1_ratio=0.15,
                               learning_rate='optimal', loss='hinge',
                               max_iter=1000, n_iter_no_change=5, n_jobs=None,
                               penalty='l2', power_t=0.5, random_state=None,
                               shuffle=True, tol=0.001, validation_fraction=0.1,
                               verbose=0, warm_start=False))],
         verbose=False)

In [163]:
predictions = sgd.predict(X_valid) 
print(classification_report(y_valid, predictions))

mae = mean_absolute_error(predictions,y_valid) 

print("Mean Absolute Error:" , mae)

C:\Users\Jayita\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           0       0.84      1.00      0.91     14848
           1       0.00      0.00      0.00      2473
           2       0.00      0.00      0.00       451

    accuracy                           0.84     17772
   macro avg       0.28      0.33      0.30     17772
weighted avg       0.70      0.84      0.76     17772

Mean Absolute Error: 0.1899054692775152


In [169]:
pred = sgd.predict(X_test)
pred=(np.around(pred,decimals=0))
pred=pred.astype(int)
pred[:5]
new_test = pd.read_csv("D:/ML on AGRICULTURE/test.csv")
result = pd.DataFrame(pred, new_test['ID'], columns=["Crop_Damage"])
result.to_csv("D:/ML on Agriculture/sgd.csv")


# LOGISTIC REGRESSION

In [138]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression()
model_lr.fit(X_train,y_train)

C:\Users\Jayita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Jayita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [139]:
predictions = model_lr.predict(X_valid) 
print(classification_report(y_valid, predictions))

mae = mean_absolute_error(predictions,y_valid) 

print("Mean Absolute Error:" , mae)

              precision    recall  f1-score   support

           0       0.84      0.99      0.91     14848
           1       0.37      0.05      0.08      2473
           2       0.00      0.00      0.00       451

    accuracy                           0.83     17772
   macro avg       0.40      0.35      0.33     17772
weighted avg       0.75      0.83      0.77     17772

Mean Absolute Error: 0.1919873959036687


C:\Users\Jayita\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [165]:
pred = model_lr.predict(X_test)
pred=(np.around(pred,decimals=0))
pred=pred.astype(int)
pred[:5]

array([0, 0, 0, 0, 0])

In [166]:
new_test = pd.read_csv("D:/ML on AGRICULTURE/test.csv")
result = pd.DataFrame(pred, new_test['ID'], columns=["Crop_Damage"])
result.to_csv("D:/ML on Agriculture/lr.csv")

In [167]:
result = pd.concat([new_test['ID'],pd.Series(pred)],axis=1)
result.columns = ['ID','Crop_Damage']
result['Crop_Damage'].value_counts()

0    58243
1     1067
Name: Crop_Damage, dtype: int64